### PR TITLE
Enhance pause detection

### LINKED ISSUE #11: Pause detection does not work properly
Just imported a hiking session which was detected as pause as a whole. So the default 10 second threshold for GPS points might not work for those type of sessions.

Pause detection need to be improved.

### PR DESCRIPTION
**Pull request by TheWudu**
An idea to improve the pause detection. Feedback appreciated

### CODE REVIEW

**Comment by erikpaperik** [comment]
Verified it with 2 MTB sessions I did.
[mtb_sessions.zip](https://github.com/TheWudu/mystats/files/9562896/mtb_sessions.zip)

Session w/ pause:
- Pause in Garmin Connect: 12min 48s
- Pause in Strava: 12min 42s
- Pause in MyStats: 12min 36s

Session w/o noticeable pause (very slow rolling):
- Pause in Garmin Connect: 3s (due to it's auto-pause feature on the device)
- Pause in Strava: 0s
- Pause in MyStats: 0s

Looks good to me :+1:

**Review by erikpaperik — APPROVED** [review]

File: lib/parser/gpx.rb [hunk 1]
```diff
@@ -42,6 +46,40 @@ def parse # rubocop:disable Metrics/AbcSize
...
+    end
+
+    def set_thresholds(points)
+      # calculate average speed
+      # and assume to slow is 1/10th of it
+      avg_speed = points.sum { |p| p[:speed] } / points.size
+      @to_slow = avg_speed / 10
+
+      # get the average durations between the gps points
+      # and remove the lower and upper 10% to remove the
```
Comment (ghsmaniotto) [inline lib/parser/gpx.rb:72]: Is there a reason for 10%? (just curious ☺️)

File: lib/parser/gpx.rb [hunk 2]
```diff
@@ -42,6 +46,40 @@ def parse # rubocop:disable Metrics/AbcSize
 
     private
 
+    def enhance_trace(points)
+      prev_point = points.first
+      points[1..].each_with_object([]) do |cur_point, et|
+        duration = cur_point[:time].to_f - prev_point[:time].to_f
```
Comment (ghsmaniotto) [inline lib/parser/gpx.rb:52]: If the user is not moving, are the GPS traces not recorded?
Or do we receive GPS with the same lat/lng?

**Review by ghsmaniotto — APPROVED** [review]
I have some general questions about the topic, otherwise, looks go to me :)

File: lib/parser/gpx.rb [hunk 3]
```diff
@@ -42,6 +46,40 @@ def parse # rubocop:disable Metrics/AbcSize
...
+        et << cur_point.merge(distance: distance, duration: duration, speed: speed)
+        prev_point = cur_point
+      end
+    end
+
+    def set_thresholds(points)
+      # calculate average speed
+      # and assume to slow is 1/10th of it
+      avg_speed = points.sum { |p| p[:speed] } / points.size
+      @to_slow = avg_speed / 10
```
Comment (Goltergaul) [inline lib/parser/gpx.rb:69]: It would be interesting to check if that would still work with ski touring. there you are veeery slow when going up, but pretty fast going down

Comment (Goltergaul) [reply lib/parser/gpx.rb:69]: this one for example: https://www.runtastic.com/de/benutzer/73412fb6-067f-ae70-caba-25969cfd75d2/sportaktivitaeten/3e8d10d8-1a75-4ae4-8e0b-fa8d02663677 it contains a long pause between 3:52 and 5:06 and two others between 3:00 - 3:25 and 2:08 - 2:21

File: lib/parser/gpx.rb (hunk 1 above)
Comment (TheWudu) [reply lib/parser/gpx.rb:72]: I just wanted to get rid of the highest and lowest values.. any other suggestion ?

File: lib/parser/gpx.rb (hunk 2 above)
Comment (TheWudu) [reply lib/parser/gpx.rb:52]: I would say: depends on the device/implementation. For Garmin it seems it does not record gps points. Runtastic is also behaving like this iirc.

File: lib/parser/gpx.rb (hunk 3 above)
Comment (TheWudu) [reply lib/parser/gpx.rb:69]: Can you try it ?

Comment (TheWudu) [reply lib/parser/gpx.rb:69]: I guess there will be some cases where the pause-detection does not work properly .. would be awesome to get examples and then enhance. :)
